### ISSUE TITLE
Update AllianceAsset for alliancev1.1.0

### ISSUE THREAD

**Issue by matpb** [noria-net/alliance-cosmwasm#1]
There was a recent update to the alliance module and a new property has been added to the `AllianceAsset`.

The new property is named `consensus_cap` and is of type `Decimal256`.

See this [struct](https://github.com/cryptechdev/alliance-contract/blob/66e0e440dc8b7f268e46ee95a96d062837610c46/src/msg.rs#LL176C15-L176C15) for reference.

**Comment by 0xForerunner** [comment]
on it!

**Comment by 0xForerunner** [comment]
444ab6e0e05b133e9c019cb4de3e2736154980e9
Done!
